PRAGMA journal_mode = WAL;
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'employee' CHECK (role IN ('manager','employee')),
  active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS settings (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  company_name TEXT NOT NULL DEFAULT '',
  address TEXT NOT NULL DEFAULT '',
  city TEXT NOT NULL DEFAULT '',
  state TEXT NOT NULL DEFAULT '',
  country TEXT NOT NULL DEFAULT 'India',
  pincode TEXT NOT NULL DEFAULT '',
  phone TEXT NOT NULL DEFAULT '',
  email TEXT NOT NULL DEFAULT '',
  website TEXT NOT NULL DEFAULT '',
  gstin TEXT NOT NULL DEFAULT '',
  pan TEXT NOT NULL DEFAULT '',
  iec TEXT NOT NULL DEFAULT '',
  logo TEXT NOT NULL DEFAULT '',
  signature TEXT NOT NULL DEFAULT '',
  default_terms TEXT NOT NULL DEFAULT '',
  quote_prefix TEXT NOT NULL DEFAULT 'QT',
  pi_prefix TEXT NOT NULL DEFAULT 'PI',
  inv_prefix TEXT NOT NULL DEFAULT 'INV',
  pl_prefix TEXT NOT NULL DEFAULT 'PL',
  bank_accounts TEXT NOT NULL DEFAULT '[]',
  arn_ref TEXT NOT NULL DEFAULT '',
  theme_color TEXT NOT NULL DEFAULT '#8b1a1a',
  quote_pattern TEXT NOT NULL DEFAULT 'QT/{FY}/{SEQ}',
  pi_pattern TEXT NOT NULL DEFAULT 'PI/{FY}/{SEQ}',
  pi_export_pattern TEXT NOT NULL DEFAULT 'EX-PI/{FY}/{SEQ}',
  inv_pattern TEXT NOT NULL DEFAULT 'INV/{FY}/{SEQ}',
  inv_export_pattern TEXT NOT NULL DEFAULT 'EX/{FY}/{SEQ}',
  pl_pattern TEXT NOT NULL DEFAULT 'PL/{FY}/{SEQ}',
  order_pattern TEXT NOT NULL DEFAULT 'SO/{FY}/{SEQ}',
  order_export_pattern TEXT NOT NULL DEFAULT 'SO-EX/{FY}/{SEQ}',
  note_presets TEXT NOT NULL DEFAULT '[]'
);
INSERT OR IGNORE INTO settings (id) VALUES (1);

CREATE TABLE IF NOT EXISTS customers (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  contact_person TEXT NOT NULL DEFAULT '',
  email TEXT NOT NULL DEFAULT '',
  phone TEXT NOT NULL DEFAULT '',
  address TEXT NOT NULL DEFAULT '',
  city TEXT NOT NULL DEFAULT '',
  country TEXT NOT NULL DEFAULT 'India',
  gstin TEXT NOT NULL DEFAULT '',
  currency TEXT NOT NULL DEFAULT 'INR',
  consignee TEXT NOT NULL DEFAULT '',
  notify_party TEXT NOT NULL DEFAULT '',
  notify_party_2 TEXT NOT NULL DEFAULT '',
  notes TEXT NOT NULL DEFAULT '',
  owner_id INTEGER REFERENCES users(id),
  is_export INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS products (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  hsn_code TEXT NOT NULL DEFAULT '',
  unit TEXT NOT NULL DEFAULT 'unit',
  unit_price REAL NOT NULL DEFAULT 0,
  country_of_origin TEXT NOT NULL DEFAULT 'India',
  image TEXT NOT NULL DEFAULT '',
  color TEXT NOT NULL DEFAULT '',
  -- Packing defaults: how the product ships and how much fills a container.
  -- The same product can exist at more than one box count, so name alone does
  -- not identify a catalogue entry — see productImport.ts.
  pcs_per_pack REAL,
  qty_20ft REAL,
  qty_40ft REAL,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS enquiries (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  customer_id INTEGER NOT NULL REFERENCES customers(id),
  date TEXT NOT NULL,
  notes TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open','quoted','lost')),
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS quotations (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  number TEXT NOT NULL,
  revision INTEGER NOT NULL DEFAULT 0,
  date TEXT NOT NULL,
  enquiry_id INTEGER REFERENCES enquiries(id),
  customer_id INTEGER NOT NULL REFERENCES customers(id),
  currency TEXT NOT NULL DEFAULT 'INR',
  validity_date TEXT NOT NULL DEFAULT '',
  payment_terms TEXT NOT NULL DEFAULT '',
  delivery_terms TEXT NOT NULL DEFAULT '',
  notes TEXT NOT NULL DEFAULT '',
  freight REAL NOT NULL DEFAULT 0,
  insurance REAL NOT NULL DEFAULT 0,
  inco_terms TEXT NOT NULL DEFAULT '',
  container_count TEXT NOT NULL DEFAULT '',
  prepared_by TEXT NOT NULL DEFAULT '',
  tax_type TEXT NOT NULL DEFAULT 'none' CHECK (tax_type IN ('none','cgst_sgst','igst')),
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','sent','negotiating','accepted','rejected','expired')),
  is_export INTEGER NOT NULL DEFAULT 0,
  created_by INTEGER REFERENCES users(id),
  approval_status TEXT NOT NULL DEFAULT 'not_submitted' CHECK (approval_status IN ('not_submitted','pending','approved','rejected')),
  approved_by INTEGER REFERENCES users(id),
  approved_at TEXT NOT NULL DEFAULT '',
  approval_note TEXT NOT NULL DEFAULT '',
  column_config TEXT NOT NULL DEFAULT '{}',
  subtotal REAL NOT NULL DEFAULT 0,
  tax_total REAL NOT NULL DEFAULT 0,
  grand_total REAL NOT NULL DEFAULT 0,
  superseded_by INTEGER REFERENCES quotations(id),
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS quotation_items (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  quotation_id INTEGER NOT NULL REFERENCES quotations(id) ON DELETE CASCADE,
  product_id INTEGER REFERENCES products(id),
  description TEXT NOT NULL DEFAULT '',
  hsn_code TEXT NOT NULL DEFAULT '',
  qty REAL,
  unit TEXT NOT NULL DEFAULT 'unit',
  unit_price REAL NOT NULL DEFAULT 0,
  tax_pct REAL NOT NULL DEFAULT 0,
  amount REAL NOT NULL DEFAULT 0,
  color TEXT NOT NULL DEFAULT '',
  packs REAL,
  pcs_per_pack REAL,
  total_pcs REAL,
  custom1 TEXT NOT NULL DEFAULT '',
  custom2 TEXT NOT NULL DEFAULT '',
  custom3 TEXT NOT NULL DEFAULT '',
  sort_order INTEGER NOT NULL DEFAULT 0
);

-- The order book: what the customer has committed to buy, tracked from intake
-- through production to dispatch. Sits between quotation and proforma invoice.
CREATE TABLE IF NOT EXISTS orders (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  number TEXT NOT NULL,
  date TEXT NOT NULL,
  quotation_id INTEGER REFERENCES quotations(id),
  customer_id INTEGER NOT NULL REFERENCES customers(id),
  is_export INTEGER NOT NULL DEFAULT 0,
  order_through TEXT NOT NULL DEFAULT '',
  spoc TEXT NOT NULL DEFAULT '',
  po_number TEXT NOT NULL DEFAULT '',
  po_date TEXT NOT NULL DEFAULT '',
  currency TEXT NOT NULL DEFAULT 'INR',
  tax_type TEXT NOT NULL DEFAULT 'none' CHECK (tax_type IN ('none','cgst_sgst','igst')),
  payment_terms TEXT NOT NULL DEFAULT '',
  freight REAL NOT NULL DEFAULT 0,
  insurance REAL NOT NULL DEFAULT 0,
  inco_terms TEXT NOT NULL DEFAULT '',
  container_count TEXT NOT NULL DEFAULT '',
  advance_due REAL NOT NULL DEFAULT 0,
  advance_amount REAL NOT NULL DEFAULT 0,
  advance_received_date TEXT NOT NULL DEFAULT '',
  destination TEXT NOT NULL DEFAULT '',
  transport TEXT NOT NULL DEFAULT '',
  freight_terms TEXT NOT NULL DEFAULT '',
  promised_date TEXT NOT NULL DEFAULT '',
  scheduled_date TEXT NOT NULL DEFAULT '',
  revised_date TEXT NOT NULL DEFAULT '',
  actual_production_date TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','confirmed','scheduled','in_production','ready','partially_dispatched','completed','cancelled')),
  remarks TEXT NOT NULL DEFAULT '',
  notes TEXT NOT NULL DEFAULT '',
  column_config TEXT NOT NULL DEFAULT '{}',
  created_by INTEGER REFERENCES users(id),
  subtotal REAL NOT NULL DEFAULT 0,
  tax_total REAL NOT NULL DEFAULT 0,
  grand_total REAL NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS order_items (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  product_id INTEGER REFERENCES products(id),
  description TEXT NOT NULL DEFAULT '',
  hsn_code TEXT NOT NULL DEFAULT '',
  code TEXT NOT NULL DEFAULT '',
  qty REAL,
  unit TEXT NOT NULL DEFAULT 'unit',
  unit_price REAL NOT NULL DEFAULT 0,
  tax_pct REAL NOT NULL DEFAULT 0,
  amount REAL NOT NULL DEFAULT 0,
  color TEXT NOT NULL DEFAULT '',
  packs REAL,
  pcs_per_pack REAL,
  total_pcs REAL,
  supplier TEXT NOT NULL DEFAULT '',
  scheduled_date TEXT NOT NULL DEFAULT '',
  dispatched_date TEXT NOT NULL DEFAULT '',
  custom1 TEXT NOT NULL DEFAULT '',
  custom2 TEXT NOT NULL DEFAULT '',
  custom3 TEXT NOT NULL DEFAULT '',
  sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS proforma_invoices (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  number TEXT NOT NULL,
  date TEXT NOT NULL,
  quotation_id INTEGER REFERENCES quotations(id),
  order_id INTEGER REFERENCES orders(id),
  customer_id INTEGER NOT NULL REFERENCES customers(id),
  consignee TEXT NOT NULL DEFAULT '',
  notify_party TEXT NOT NULL DEFAULT '',
  currency TEXT NOT NULL DEFAULT 'INR',
  freight REAL NOT NULL DEFAULT 0,
  insurance REAL NOT NULL DEFAULT 0,
  lead_time TEXT NOT NULL DEFAULT '',
  bank_account TEXT NOT NULL DEFAULT '',
  inco_terms TEXT NOT NULL DEFAULT '',
  payment_terms TEXT NOT NULL DEFAULT '',
  delivery_terms TEXT NOT NULL DEFAULT '',
  validity_date TEXT NOT NULL DEFAULT '',
  is_export INTEGER NOT NULL DEFAULT 0,
  country_of_origin TEXT NOT NULL DEFAULT '',
  port_of_loading TEXT NOT NULL DEFAULT '',
  port_of_discharge TEXT NOT NULL DEFAULT '',
  final_destination TEXT NOT NULL DEFAULT '',
  container_count TEXT NOT NULL DEFAULT '',
  partial_shipment TEXT NOT NULL DEFAULT 'Not Allowed',
  po_number TEXT NOT NULL DEFAULT '',
  po_date TEXT NOT NULL DEFAULT '',
  notify_party_2 TEXT NOT NULL DEFAULT '',
  method_of_despatch TEXT NOT NULL DEFAULT '',
  quantity_tolerance TEXT NOT NULL DEFAULT '',
  hs_code TEXT NOT NULL DEFAULT '',
  prepared_by TEXT NOT NULL DEFAULT '',
  remarks TEXT NOT NULL DEFAULT '',
  tax_type TEXT NOT NULL DEFAULT 'none' CHECK (tax_type IN ('none','cgst_sgst','igst')),
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','sent','order_confirmed','advance_received','in_production','cancelled')),
  created_by INTEGER REFERENCES users(id),
  approval_status TEXT NOT NULL DEFAULT 'not_submitted' CHECK (approval_status IN ('not_submitted','pending','approved','rejected')),
  approved_by INTEGER REFERENCES users(id),
  approved_at TEXT NOT NULL DEFAULT '',
  approval_note TEXT NOT NULL DEFAULT '',
  column_config TEXT NOT NULL DEFAULT '{}',
  subtotal REAL NOT NULL DEFAULT 0,
  tax_total REAL NOT NULL DEFAULT 0,
  grand_total REAL NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS pi_items (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  pi_id INTEGER NOT NULL REFERENCES proforma_invoices(id) ON DELETE CASCADE,
  product_id INTEGER REFERENCES products(id),
  description TEXT NOT NULL DEFAULT '',
  hsn_code TEXT NOT NULL DEFAULT '',
  qty REAL,
  unit TEXT NOT NULL DEFAULT 'unit',
  unit_price REAL NOT NULL DEFAULT 0,
  tax_pct REAL NOT NULL DEFAULT 0,
  amount REAL NOT NULL DEFAULT 0,
  color TEXT NOT NULL DEFAULT '',
  packs REAL,
  pcs_per_pack REAL,
  total_pcs REAL,
  custom1 TEXT NOT NULL DEFAULT '',
  custom2 TEXT NOT NULL DEFAULT '',
  custom3 TEXT NOT NULL DEFAULT '',
  sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS commercial_invoices (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  number TEXT NOT NULL,
  date TEXT NOT NULL,
  pi_id INTEGER REFERENCES proforma_invoices(id),
  order_id INTEGER REFERENCES orders(id),
  customer_id INTEGER NOT NULL REFERENCES customers(id),
  consignee TEXT NOT NULL DEFAULT '',
  notify_party TEXT NOT NULL DEFAULT '',
  currency TEXT NOT NULL DEFAULT 'INR',
  freight REAL NOT NULL DEFAULT 0,
  insurance REAL NOT NULL DEFAULT 0,
  shipping_details TEXT NOT NULL DEFAULT '',
  bank_account TEXT NOT NULL DEFAULT '',
  inco_terms TEXT NOT NULL DEFAULT '',
  payment_terms TEXT NOT NULL DEFAULT '',
  is_export INTEGER NOT NULL DEFAULT 0,
  country_of_origin TEXT NOT NULL DEFAULT '',
  port_of_loading TEXT NOT NULL DEFAULT '',
  port_of_discharge TEXT NOT NULL DEFAULT '',
  final_destination TEXT NOT NULL DEFAULT '',
  notify_party_2 TEXT NOT NULL DEFAULT '',
  method_of_despatch TEXT NOT NULL DEFAULT '',
  lot_no TEXT NOT NULL DEFAULT '',
  prepared_by TEXT NOT NULL DEFAULT '',
  remarks TEXT NOT NULL DEFAULT '',
  tax_type TEXT NOT NULL DEFAULT 'none' CHECK (tax_type IN ('none','cgst_sgst','igst')),
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','final','dispatched','paid')),
  created_by INTEGER REFERENCES users(id),
  approval_status TEXT NOT NULL DEFAULT 'not_submitted' CHECK (approval_status IN ('not_submitted','pending','approved','rejected')),
  approved_by INTEGER REFERENCES users(id),
  approved_at TEXT NOT NULL DEFAULT '',
  approval_note TEXT NOT NULL DEFAULT '',
  column_config TEXT NOT NULL DEFAULT '{}',
  subtotal REAL NOT NULL DEFAULT 0,
  tax_total REAL NOT NULL DEFAULT 0,
  grand_total REAL NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS invoice_items (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  invoice_id INTEGER NOT NULL REFERENCES commercial_invoices(id) ON DELETE CASCADE,
  product_id INTEGER REFERENCES products(id),
  description TEXT NOT NULL DEFAULT '',
  hsn_code TEXT NOT NULL DEFAULT '',
  qty REAL,
  unit TEXT NOT NULL DEFAULT 'unit',
  unit_price REAL NOT NULL DEFAULT 0,
  tax_pct REAL NOT NULL DEFAULT 0,
  amount REAL NOT NULL DEFAULT 0,
  color TEXT NOT NULL DEFAULT '',
  packs REAL,
  pcs_per_pack REAL,
  total_pcs REAL,
  custom1 TEXT NOT NULL DEFAULT '',
  custom2 TEXT NOT NULL DEFAULT '',
  custom3 TEXT NOT NULL DEFAULT '',
  sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS packing_lists (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  number TEXT NOT NULL,
  date TEXT NOT NULL,
  invoice_id INTEGER REFERENCES commercial_invoices(id),
  customer_id INTEGER NOT NULL REFERENCES customers(id),
  shipping_marks TEXT NOT NULL DEFAULT '',
  lot_no TEXT NOT NULL DEFAULT '',
  remarks TEXT NOT NULL DEFAULT '',
  created_by INTEGER REFERENCES users(id),
  column_config TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS packing_list_items (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  packing_list_id INTEGER NOT NULL REFERENCES packing_lists(id) ON DELETE CASCADE,
  hsn_code TEXT NOT NULL DEFAULT '',
  description TEXT NOT NULL DEFAULT '',
  qty REAL,
  unit TEXT NOT NULL DEFAULT 'unit',
  packages TEXT NOT NULL DEFAULT '',
  dimensions TEXT NOT NULL DEFAULT '',
  gross_weight REAL NOT NULL DEFAULT 0,
  net_weight REAL NOT NULL DEFAULT 0,
  custom1 TEXT NOT NULL DEFAULT '',
  custom2 TEXT NOT NULL DEFAULT '',
  custom3 TEXT NOT NULL DEFAULT '',
  sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS followups (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  doc_type TEXT NOT NULL CHECK (doc_type IN ('enquiry','quotation','proforma','invoice','general')),
  doc_id INTEGER,
  customer_id INTEGER REFERENCES customers(id),
  due_date TEXT NOT NULL,
  note TEXT NOT NULL DEFAULT '',
  done INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS payments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  pi_id INTEGER REFERENCES proforma_invoices(id),
  invoice_id INTEGER REFERENCES commercial_invoices(id),
  customer_id INTEGER REFERENCES customers(id),
  date TEXT NOT NULL,
  amount REAL NOT NULL,
  currency TEXT NOT NULL DEFAULT 'INR',
  method TEXT NOT NULL DEFAULT '',
  reference TEXT NOT NULL DEFAULT '',
  notes TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS sequences (
  doc_type TEXT NOT NULL,
  year INTEGER NOT NULL,
  next_num INTEGER NOT NULL DEFAULT 1,
  PRIMARY KEY (doc_type, year)
);
